type VCard {
    id: ID!
    c1: String!
    c2: String!
    c3: String!
    rec: String!
    sender: String!
    msg: String!
    link: String!
  }
   type Query {
    getVCard: [VCard]

    GetVCardLink(link: String): VCard
  }

    
  
  